### ISSUE TITLE
Are you aware of existing project which also does roughly same, and its supporting library with same name?

### ISSUE THREAD

**Issue by tribals** [stef/pbp#23]
- https://github.com/withoutboats/pbp
- https://github.com/withoutboats/bpb

**Comment by stef** [comment]
heh, they are like 4 years late to the namespace-ignorant collision party, also it seems they do much much less than pbp. i'm kinda used to people "stealing" my names, so i guess *shrug*? or what do you expect here?

**Comment by tribals** [comment]
Nothing special. I'm not sure who is firs at binding names. My point is that it is difficult to find projects when they have same name, but, as those projects from different technologies, so this could be not a problem. The hard part is that projects share not only names, but the intent also.
